spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://wwwarindumesanda_db_user:aVFSjEloUm75M1m8@cluster0.ampjh7o.mongodb.net/paf_db?retryWrites=true&w=majority

spring.data.mongodb.database=paf_db

server.port=8080